//auth action type
export const SUCCESS_SIGN_UP='SUCCESS_SIGN_UP';
export const SUCCESS_LOGIN='SUCCESS_LOGIN';
export const SUCCESS_LOGOUT='SUCCESS_LOGOUT';
export const SET_USER='SET_USER'


//pdf post action types
export const ADD_PDF_LIST='ADD_PDF_LIST'
export const ADD_PDF_TO_LIST='ADD_PDF_TO_LIST'
export const DELETE_PDF_TO_LIST='DELETE_PDF_TO_LIST'
export const SHOW_SELECTED_PDF='SHOW_SELECTED_PDF'

//pdf post action types
export const ADD_PDF_VERSION_LIST='ADD_PDF_VERSION_LIST'
export const ADD_PDF_VERSION_TO_LIST='ADD_PDF_VERSION_TO_LIST'
export const DELETE_PDF_VERSION_TO_LIST='DELETE_PDF_VERSION_TO_LIST'
export const SHOW_PDF_VERSION_EDITOR='SHOW_PDF_VERSION_EDITOR' 